--general
E2Helper.Descriptions["acfCustomIsEngine"] = "Returns 1 if the entity is an ACF Custom engine."
E2Helper.Descriptions["acfCustomIsGearbox"] = "Returns 1 if the entity is an ACF Custom gearbox."
E2Helper.Descriptions["acfCustomActive"] = "Gets/sets Active (0-1) for an ACF Custom engine, ammo crate, or fuel tank."
E2Helper.Descriptions["acfCustomNameShort"] = "Returns the short name of an ACF Custom entity."
E2Helper.Descriptions["acfCustomName"] = "Returns the full name of an ACF Custom entity."
E2Helper.Descriptions["acfCustomType"] = "Returns the type of ACF Custom entity."
E2Helper.Descriptions["acfCustomInfoRestricted"] = "Returns 1 if functions returning sensitive info are restricted to owned props."
E2Helper.Descriptions["acfCustomLinks"] = "Returns all the entities which are linked to this entity through ACF Custom."

--engine
E2Helper.Descriptions["acfCustomMaxTorque"] = "Returns the maximum torque (in N/m) of an ACF Custom engine."
E2Helper.Descriptions["acfCustomMaxPower"] = "Returns the maximum power (in kW) of an ACF Custom engine."
E2Helper.Descriptions["acfCustomIdleRPM"] = "Returns the idle RPM of an ACF Custom engine."
E2Helper.Descriptions["acfCustomPowerbandMin"] = "Returns the powerband minimum of an ACF Custom engine."
E2Helper.Descriptions["acfCustomPowerbandMax"] = "Returns the powerband maximum of an ACF Custom engine."
E2Helper.Descriptions["acfCustomRedline"] = "Returns the redline RPM of an ACF Custom engine."
E2Helper.Descriptions["acfCustomRPM"] = "Returns the current RPM of an ACF Custom engine."
E2Helper.Descriptions["acfCustomTorque"] = "Returns the current torque (in N/m) of an ACF Custom engine."
E2Helper.Descriptions["acfCustomPower"] = "Returns the current power (in kW) of an ACF Custom engine."
E2Helper.Descriptions["acfCustomInPowerband"] = "Returns 1 if the ACF Custom engine RPM is inside the powerband."
E2Helper.Descriptions["acfCustomThrottle"] = "Gets/sets Throttle (0-100) for an ACF Custom engine."
E2Helper.Descriptions["acfCustomTqAdd"] = "Sets Torque Add for an ACF Custom engine."
E2Helper.Descriptions["acfCustomRpmAdd"] = "Add Rpm for an ACF Custom engine."
E2Helper.Descriptions["acfCustomFlywheelMass"] = "Sets Flywheel Mass for an ACF Custom engine."
E2Helper.Descriptions["acfCustomIdle"] = "Sets Idle Rpm for an ACF Custom engine."
E2Helper.Descriptions["acfCustomDisableCut"] = "Sets Disable Cutoff(rev limiter) for an ACF Custom engine."

--gearbox
E2Helper.Descriptions["acfCustomGear"] = "Returns the current gear of an ACF Custom gearbox."
E2Helper.Descriptions["acfCustomNumGears"] = "Returns the number of gears of an ACF Custom gearbox."
E2Helper.Descriptions["acfCustomFinalRatio"] = "Returns the final ratio of an ACF Custom gearbox."
E2Helper.Descriptions["acfCustomTorqueRating"] = "Returns the maximum torque (in N/m) an ACF Custom gearbox can handle."
E2Helper.Descriptions["acfCustomIsDual"] = "Returns 1 if an ACF gearbox is dual clutch."
E2Helper.Descriptions["acfCustomShiftTime"] = "Returns the time in ms an ACF Custom gearbox takes to change gears."
E2Helper.Descriptions["acfCustomInGear"] = "Returns 1 if an ACF gearbox is in gear."
E2Helper.Descriptions["acfCustomTotalRatio"] = "Returns the total ratio (current gear * final) of an ACF Custom gearbox."
E2Helper.Descriptions["acfCustomGearRatio"] = "Returns the ratio of a specified gear of an ACF Custom gearbox."
E2Helper.Descriptions["acfCustomTorqueOut"] = "Returns the current torque output (in N/m) an ACF Custom gearbox. A bit jumpy due to how ACF applies power."
E2Helper.Descriptions["acfCustomShift"] = "Shift to the specified gear for an ACF Custom gearbox."
E2Helper.Descriptions["acfCustomShiftUp"] = "Set an ACF Custom gearbox to shift up."
E2Helper.Descriptions["acfCustomShiftDown"] = "Set an ACF Custom gearbox to shift down."
E2Helper.Descriptions["acfCustomBrake"] = "Sets the brake for an ACF Custom gearbox. Sets both sides of a dual clutch gearbox."
E2Helper.Descriptions["acfCustomBrakeLeft"] = "Sets the left brake for an ACF Custom gearbox. Only works for dual clutch."
E2Helper.Descriptions["acfCustomBrakeRight"] = "Sets the right brake for an ACF Custom gearbox. Only works for dual clutch."
E2Helper.Descriptions["acfCustomClutch"] = "Sets the clutch for an ACF Custom gearbox. Sets both sides of a dual clutch gearbox."
E2Helper.Descriptions["acfCustomClutchLeft"] = "Sets the left clutch for an ACF Custom gearbox. Only works for dual clutch."
E2Helper.Descriptions["acfCustomClutchRight"] = "Sets the right clutch for an ACF Custom gearbox. Only works for dual clutch."
